name: Release action 2
# Call the reusable workflow release-solution-with-inputs2.yml
# Release your solution to prod when you create a new release.

on:
  release:
      types: [created]        
permissions:
  contents: write
jobs:
  Release-solution-ALMLab:
    uses: ./.github/workflows/release-solution-to-prod-with-inputs.yml
    with:
      #You can specify the solution name here
      solution_name: ALMLab5
      #Update your values here
      BUILD_ENVIRONMENT_URL: 'https://org73420444.crm.dynamics.com'
      PRODUCTION_ENVIRONMENT_URL: 'https://oko-prod.crm.dynamics.com'
      CLIENT_ID: '2828ef51-b310-487b-986a-a3995e830e7b'
      TENANT_ID: '7e955522-254c-47cc-9b28-8c7d595082a2'      
    secrets:
      envSecret: ${{ secrets.PowerPlatformSPN }}
